version: '3.7'
services:
    db:
        volumes:
            - './docker/mysql/my.cnf:/etc/mysql/my.cnf:ro'
    php:
        volumes:
            - './app/:/usr/src/app'
    nginx:
        volumes:
            - './app/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
    adminer:
        ports:
            - '${ADMINER_PORT}:8080'
